---
language: rust
cache: cargo
before_cache:
  - rm -rfv target/debug/.fingerprint/mend-rs-*

rust: nightly

sudo: false

branches:
  only:
    - staging
    - trying
    - master

env:
  global:
    - RUST_BACKTRACE=full
    - OPENSSL_STATIC=1

script:
  - rustc -vV
  - cargo test --all
  - cargo build --release

before_deploy:
  - mkdir $TRAVIS_BUILD_DIR/build_result
  - cp $TRAVIS_BUILD_DIR/target/release/mend-rs $TRAVIS_BUILD_DIR/build_result/mend-rs-master
  - cp $TRAVIS_BUILD_DIR/target/release/mend-rs $TRAVIS_BUILD_DIR/build_result/mend-rs-$TRAVIS_COMMIT

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: $TRAVIS_BUILD_DIR/build_result/
  upload_dir: builds
