---
language: rust
cache: cargo

rust: nightly
addons:
  artifacts:
    s3_region: "eu-central-1"
    working_dir: target/release
    paths:
      - mend-rs

sudo: false

branches:
  only:
    - staging
    - trying
    - master

env:
  global:
    - RUST_BACKTRACE=full

script:
  - rustc -vV
  - cargo test --all
  - cargo build --release
