---
language: rust
cache: cargo

rust: nightly

sudo: false


branches:
  only:
    - staging
    - trying
    - master

env:
 global:
   - RUST_BACKTRACE=full

script:
  - rustc -vV
  - cargo test --all
