---
language: rust
cache: cargo

rust: nightly

sudo: false

branches:
  only:
    - staging
    - trying
    - master

env:
  global:
    - RUST_BACKTRACE=full

script:
  - rustc -vV
  - cargo test --all
  - cargo build --release

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: $HOME/mend-rs/target/release/mend-rs
  upload_dir: builds
